const app = new Vue({
    el: '#app',
    data: {
        chiSiamo1: 'Lo studio AMPIA nasce per iniziativa di un’équipe specializzata di medici, psicologi, psicoterapeuti, di formazione psicodinamica ed esperienza consolidata in età evolutiva e genitorialità.',
        chiSiamo2:'L’équipe rivolge la propria attenzione all’età pediatrica, dalla primissima infanzia all’adolescenza, nonché alle famiglie di neonati, bambini e ragazzi che abbiano necessità di un’attenzione specifica, competente e scrupolosa alla propria funzione genitoriale e non solo.',
        chiSiamo3:'I professionisti, ciascuno con specificità professionale particolare, si avvalgono costantemente della collaborazione, del confronto e della supervisione di colleghi - in contesti istituzionali e non - e di altre figure operanti in ambito pediatrico,allo scopo di perseguire un approccio completo, complesso e multidisciplinare nella presa in carico dei pazienti. Pazienti e famiglie hanno pertanto occasione di essere seguiti adeguatamente in tutte le fasi della crescita: dalla gravidanza all’età neonatale, dalla prima infanzia all’età adolescenziale, all’età adulta.',
        chiSiamo4: 'I servizi dello studio AMPIA prevedono percorsi di intervento clinico di breve e lungo corso, nonché proposte di informazione e formazione, dedicate a famiglie e ad operatori impegnati in ambito infantile ed evolutivo, in contesti scolastici, sportivi, ludico-ricreativi e sanitari, tra gli altri,anche in considerazione delle richieste degli utenti. ',
        
        sostegno1: 'Il Sostegno Psicologico Individuale ha come obiettivo il miglioramento della qualità della vita ed è indirizzato a coloro che attraversano un periodo di disagio o sofferenza psichica; si tratta di un intervento volto ad accogliere le difficoltà, nel quale il paziente ha occasione di sperimentare insieme al terapeuta una modalità di adattamento più efficace. Il sostegno è declinato differentemente in base alle caratteristiche individuali di ciascuno e lo strumento principe è il colloquio clinico. In caso di lavoro con minori, dal momento che gioco e disegno rappresentano un canale espressivo ricchissimo, vengono comunemente utilizzati colori, materiali di gioco e di manipolazione libera.',
        sostegno2: 'Attraverso la Psicoterapia Individuale il terapeuta accompagna il paziente in un percorso di conoscenza di        sè,di  acquisizione di consapevolezza del proprio modo di pensare e di agire. Il terapeuta lavora con il paziente avvalendosi anzitutto sulle sue capacità individuali, in modo da rafforzare, sviluppare, promuovere le risorse interne che gli sono necessarie per superare le tappe evolutive e gli eventi critici dell’esistenza. Chi soffre, quindi, scorge nuove possibilità di dirimere i propri conflitti profondi, durante un percorso psicoterapeutico, che si contraddistingue proprio per la qualità  dell’esperienza relazionale che viene vissuta insieme al terapeuta. Accogliere e riconoscere l’altro anche nella sua sofferenza, specie quando non abbia trovato sufficiente ascolto altrove, è prerogativa fondamentale di questo lavoro.',
        sostegno3: 'La stanza di terapia per bambini e adolescenti è allestita in modo peculiare, allo scopo di predisporre un’atmosfera che faciliti l’espressione dei vissuti dei giovani pazienti. I professionisti dell’équipe hanno pluriennale        esperienza nella tecnica dell’interpretazione del gioco, strumento indispensabile per lavorare con bambini anche molto piccoli.',
        sostegno4:'Così come per gli adulti e per gli adolescenti, l’obiettivo della psicoterapia infantile è rendere possibile la comprensione delle fantasie e delle angosce dei piccoli pazienti e aiutarli a sviluppare gli strumenti necessari ad affrontare la crescita e le difficoltà ad essa connesse. Laddove si renda opportuno sarà possibile collaborare con altre figure        professionali in un’ottica di presa in carico multidisciplinare.'
    }
})